#!/bin/bash
# Run pipeline on desired image

# SEGMENTATION

# Ask user for NIFTY file path
echo 'Enter folder where desired image is (FSRTCASE_XXX.nii.gz)'
read inputFolder
mkdir -p $inputFolder/../outputTest

# nnUNet_predict -i $inputFolder -o $inputFolder/results -t 502 -m 3d_fullres --save_npz

# New NIFTY saved in $inputFolder/../outputTest, we need to access it here to open in slicer for viewing if possible

# FEATURE EXTRACTION

python extraction.py $inputFolder $inputFolder/../outputTest

# CSV of features saved at ../inputFolder level
# Normalize feature and remove colinear features in csv



# SURVIVAL PREDICTION

# Give pre-processed csv to survival prediction model

# Output graph of survival prediction

#echo Hello, who\'s this?

#read name

#echo Hey $name!
